source 'http://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.4.5'

gem 'rails', '~> 5.2.2', '>= 5.2.2.1'
gem 'sqlite3', '~> 1.3.6'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.1.0', require: false


group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 3.5'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do 
  gem 'factory_bot_rails', '~> 4.0'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'faker'
  gem 'database_cleaner'
end

#access to postgres
gem 'pg'

#generate documentation
gem 'sdoc'

#manage secure password
gem 'bcrypt', '~> 3.1.7'

#encode and decode token
gem 'jwt'

#call to authorization and authentication
gem 'simple_command'

#midware to configure headers to enable cross request
gem 'rack-cors'